export const projects = [
  {
    name: "chat-app",
    summary:
      "Designed and implemented a dynamic chat application with React and Express JS, featuring user authentication, contact management, and real-time communication via Socket.IO. Prioritized an intuitive interface for an engaging and efficient chat experience.",
    image: "/chat-app.jpg",
    description: [
      "In crafting a dynamic chat application using React, I focused on user authentication (sign in/Signup), contact management (add/search contacts), and real-time bidirectional communication using socket.io. Leveraging Express JS for the backend, I prioritized scalability and efficient data management. The project also involved implementing a clean and intuitive user interface, enhancing the overall user experience.",
    ],
    technologies: [
      "React JS",
      "JavaScript",
      "Redux toolkit",
      "HTML5",
      "CSS3",
      "Bootstrap",
      "Node Js",
      "Express JS",
      "MongoDB",
      "Socket.IO",
      "React hooks",
      "GitHub",
      "Git",
      "MongoDB Atlas",
    ],
    github: "https://github.com/sandeep-reddy1101/chat-app-react",
    live: "",
  },
  {
    name: "e-Commerce",
    summary:
      "Developed a feature-rich e-commerce platform using React and Express JS, integrating user authentication, product management, and secure Stripe payments. Ensured a seamless user experience with responsive design, contributing to effective online shopping.",
    image: "/e-commerce.png",
    description: [
      "I developed a robust e-commerce website using React, featuring essential functionalities such as user signup, login, product display, search, cart management, and secure checkout with Stripe payment integration. The backend API, built with Express JS, ensures seamless handling of user and cart information. Throughout the project, I implemented responsive design principles to optimize the user experience across devices.",
    ],
    technologies: [
      "React JS",
      "JavaScript",
      "Redux toolkit",
      "HTML5",
      "CSS3",
      "Bootstrap",
      "Node Js",
      "Express JS",
      "MongoDB",
      "React hooks",
      "GitHub",
      "Git",
      "MongoDB Atlas",
    ],
    github: "https://github.com/sandeep-reddy1101/e-commerce",
    live: "https://e-commerce-365.netlify.app/",
  },
];
